variable "bucket_name" {}
variable "bucket_logging_fe_name" {}
variable "counter_table_name" {}
variable "dns_record_ttl" {}
variable "force_destroy" {}
variable "github_actions_role_fe_policy" {}
variable "github_actions_url" {}
variable "http_api_stage_name" {}
variable "iam_role_name" {}
variable "iam_user_name" {}
variable "index_document" {}
variable "region" {}
variable "root_domain" {}
variable "table_name" {}
variable "terraform_frontend_policy" {}
variable "versioning_enabled" {}
variable "website_bucket" {}
